package app.jiyun.com.testsqlitegd;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huanpet.huanpet.bean.MyLoginBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_LOGIN_BEAN".
*/
public class MyLoginBeanDao extends AbstractDao<MyLoginBean, Long> {

    public static final String TABLENAME = "MY_LOGIN_BEAN";

    /**
     * Properties of entity MyLoginBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserPhone = new Property(1, String.class, "userPhone", false, "USER_PHONE");
        public final static Property Passwork = new Property(2, String.class, "passwork", false, "PASSWORK");
    }


    public MyLoginBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MyLoginBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_LOGIN_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_PHONE\" TEXT," + // 1: userPhone
                "\"PASSWORK\" TEXT);"); // 2: passwork
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_LOGIN_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyLoginBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userPhone = entity.getUserPhone();
        if (userPhone != null) {
            stmt.bindString(2, userPhone);
        }
 
        String passwork = entity.getPasswork();
        if (passwork != null) {
            stmt.bindString(3, passwork);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyLoginBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userPhone = entity.getUserPhone();
        if (userPhone != null) {
            stmt.bindString(2, userPhone);
        }
 
        String passwork = entity.getPasswork();
        if (passwork != null) {
            stmt.bindString(3, passwork);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MyLoginBean readEntity(Cursor cursor, int offset) {
        MyLoginBean entity = new MyLoginBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userPhone
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // passwork
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyLoginBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserPhone(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPasswork(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MyLoginBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MyLoginBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyLoginBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
