package app.jiyun.com.testsqlitegd;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huanpet.huanpet.bean.UserBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_BEAN".
*/
public class UserBeanDao extends AbstractDao<UserBean, Long> {

    public static final String TABLENAME = "USER_BEAN";

    /**
     * Properties of entity UserBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Portrait = new Property(1, String.class, "portrait", false, "PORTRAIT");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Sex = new Property(3, String.class, "sex", false, "SEX");
        public final static Property Natality = new Property(4, String.class, "natality", false, "NATALITY");
        public final static Property Phono = new Property(5, String.class, "phono", false, "PHONO");
        public final static Property WeiXin = new Property(6, String.class, "WeiXin", false, "WEI_XIN");
        public final static Property Qq = new Property(7, String.class, "qq", false, "QQ");
        public final static Property Location = new Property(8, String.class, "location", false, "LOCATION");
    }


    public UserBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UserBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PORTRAIT\" TEXT," + // 1: portrait
                "\"NAME\" TEXT," + // 2: name
                "\"SEX\" TEXT," + // 3: sex
                "\"NATALITY\" TEXT," + // 4: natality
                "\"PHONO\" TEXT," + // 5: phono
                "\"WEI_XIN\" TEXT," + // 6: WeiXin
                "\"QQ\" TEXT," + // 7: qq
                "\"LOCATION\" TEXT);"); // 8: location
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(2, portrait);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(4, sex);
        }
 
        String natality = entity.getNatality();
        if (natality != null) {
            stmt.bindString(5, natality);
        }
 
        String phono = entity.getPhono();
        if (phono != null) {
            stmt.bindString(6, phono);
        }
 
        String WeiXin = entity.getWeiXin();
        if (WeiXin != null) {
            stmt.bindString(7, WeiXin);
        }
 
        String qq = entity.getQq();
        if (qq != null) {
            stmt.bindString(8, qq);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(9, location);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(2, portrait);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(4, sex);
        }
 
        String natality = entity.getNatality();
        if (natality != null) {
            stmt.bindString(5, natality);
        }
 
        String phono = entity.getPhono();
        if (phono != null) {
            stmt.bindString(6, phono);
        }
 
        String WeiXin = entity.getWeiXin();
        if (WeiXin != null) {
            stmt.bindString(7, WeiXin);
        }
 
        String qq = entity.getQq();
        if (qq != null) {
            stmt.bindString(8, qq);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(9, location);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserBean readEntity(Cursor cursor, int offset) {
        UserBean entity = new UserBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // portrait
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // natality
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // phono
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // WeiXin
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // qq
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // location
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPortrait(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSex(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNatality(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPhono(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWeiXin(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setQq(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setLocation(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
